# Generated by Django 5.0.3 on 2024-03-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=40)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_address', models.CharField(max_length=200)),
            ],
        ),
    ]
