# Generated by Django 5.0.3 on 2024-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contact_phone',
            field=models.IntegerField(default=0),
        ),
    ]
